version: '3.8'

services:
  remote-desktop:
    image: remote-desktop-custom-v2
    container_name: remote-desktop
    ports:
      - "80:3389"
    deploy:
      resources:
        limits:
          memory: 4g
    restart: unless-stopped
